services:
  - type: web
    name: convenience-store-v2
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /payment/*
        destination: /index.html
      - type: rewrite
        source: /customer/*
        destination: /index.html
      - type: rewrite
        source: /store/*
        destination: /index.html
      - type: rewrite
        source: /hq/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html